name: 'Composite Action'
description: 'A custom composite action'
inputs:
  name:
    description: 'The name to greet'
    required: true
runs:
  using: 'composite'
  steps:
    - name: Print greeting
      run: echo "Hello, ${{ inputs.name }}!"
    - name: Print current date
      run: date