name: Sequential Jobs
on:
    push:
        branches:
            - main
jobs:
  parallel-job-1:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run parallel job 1
        run: echo "Running parallel job 1"

  parallel-job-2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
  sequential-job:
    runs-on: ubuntu-latest
    needs: [parallel-job-1, parallel-job-2]
    steps:
      - uses: actions/checkout@v2
      - name: Run sequential job
        run: echo "Running sequential job"