name: Custom Actions
on:
    push:
        branches:
            - main
jobs:
  custom-js-action:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run custom JavaScript action
        uses: ./.github/actions/custom-js-action
        with:
          name: 'GitHub Actions Workshop'